### ISSUE TITLE
Failed test

### ISSUE THREAD

**Issue by tramxx** [openhab/openhab1-addons#1344]
When running mvn clean install i get this error:

Failed tests:   testTypeMappingDateTime_19_001(org.openhab.binding.knx.internal.config.KNXCoreTypeMa
pperTest): KNXCoreTypeMapper.toDPTValue() test failed for datapoint type "19.001" expected:<1[900-01-01 00]:00:00> but was:<1[899-12-31 17]:00:00>

**Comment by watou** [comment]
Did this issue ever get explained?  I am trying build my fork which had been building fine with `mvn clean install` before, but now this testing is failing repeatedly:

```
Tests in error: 
  testAdd(org.openhab.binding.knx.internal.bus.KNXBusReaderSchedulerTest)

Tests run: 107, Failures: 0, Errors: 1, Skipped: 0
```

Instead of just skpping tests, I would like to understand the mystery...

**Comment by Snickermicker** [comment]
The error message posted seems to be unrelated to #1344.
This issue was about  failing time conversions.

Would you mind opening a new issue and including the exception that is thrown (if any)?

**Comment by watou** [comment]
Thanks. See  #2097.  I suggest trying the `mvn clean install` build for #1344 against Java 1.6 vs. Java 1.7 to see if that makes any difference.

**Comment by neduz** [comment]
Hello,

I'm experiencing the same problem I guess (see output: https://gist.github.com/neduz/cac01021fb2e82c4bf8b#file-failed-testtypemappingdatetime_19_001)

I'm running Ubuntu 14.10, using ubuntu-packaged java:
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~utopic1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
I'm also in the CET (Europe/Brussels) timezone, I'm not sure whether that's just a coincidence or not.

I see this issue was closed, what is the solution?

**Comment by Snickermicker** [comment]
From your log output I see the output: nl_BE
Are sure you're on the latest commit?

**Comment by neduz** [comment]
I've created a new git clone in a seperate directory, Failed tests:   testTypeMappingDateTime_19_001
nl_BE.UTF8 is the locale I'm using on my (Ubuntu) system.

**Comment by StijnDS** [comment]
Change time and date settings to a different timezone then Europe/Brussels. I chose London & "mvn clean install" worked without errors.

**Comment by Snickermicker** [comment]
I believe to have finally found the issue. The last comment help tremendously. 
Actually the code works fine, but the test itself is bogus. Will propose a pull request.
