### ISSUE TITLE
Raspberry Pi and DS18B20 on GPIOs - incompatible with OneWire Binding?

### ISSUE THREAD

**Issue by Henry7** [openhab/openhab1-addons#1886]
Hi,

i've got a problem with openhab on the raspberry pi: 
I connected several temperature sensors directly to the GPIO 4 of the Raspberry Pi and they are working great over the console, e.g.:

//////////////////////////////////////////////////////////////////////////////////////////////
root@Smarthome:# cat /sys/bus/w1/devices/28-00043b8167ff/w1_slave
6c 01 55 00 7f ff 0c 10 16 : crc=16 YES
6c 01 55 00 7f ff 0c 10 16 t=22750
//////////////////////////////////////////////////////////////////////////////////////////////

But when I try to implement these sensors as an item in openHAB, like that:

//////////////////////////////////////////////////////////////////////////////////////////////
Number  Temperatur1 "Temperature [%.1f °C]"    <temperature>   { onewire="28-00043b8167ff#temperature" }
//////////////////////////////////////////////////////////////////////////////////////////////

... the web interface of openhab only shows a "- °C"

**Comment by nygma2004** [comment]
Hi Henry7,

Can you tell me how you made that work? I am not expert in Linux. I created the shell script based tutorial above. It is not working for some reason. The last line prints the wert2 line instead of evaluating it. I tried working around it, sometimes I am getting permission denied for the w1-slave file.
Anyway, I am a bit  stuck and any help will be appreciated.
