### ISSUE TITLE
Feature Request: Command TOGGLE for MQTT

### ISSUE THREAD

**Issue by renatoriolino** [openhab/openhab1-addons#2542]
I would like to have the command TOGGLE available via MQTT binding.  I have some pulsers that communicate to OH via MQTT.  Today before sending the command, I need to get the current status via REST to only them send the command with the inverse state. 

Thanks
##

**Comment by 9037568** [comment]
Everything I read says MQTT is just a messaging transport. It doesn't recognize "commands".

You could potentially implement what you want via rules or scripts.

**Comment by renatoriolino** [comment]
Sorry about that. I was not clear about that, it's not a MQTT issue.  What I mean is that OH recognizes two commands for switches only: ON and OFF.   If I want to implement a TOGGLE, I need to make a rule for every switch to first read it state and then invert it. If I could just send TOGGLE to a switch (by MQTT, TCP, REST, etc..) would make it easier. 

It's not specific to MQTT. 
Thanks

**Comment by watou** [comment]
Both the REST API and the ClassicUI command servlet add the extra "sugar" of supporting "TOGGLE" as a command.  Since it's not a core concept, each and every layer over sending OnOffType Commands would have to explicitly add toggle support, or if SwitchItem were to accept a ToggleType Command, this could be normalized. It can't be added to the MQTT binding without breaking the rule of not inspecting item states.

**Comment by 9037568** [comment]
There's the information we needed.  Thanks!

**Comment by watou** [comment]
@renatoriolino You might consider discussing this at https://eclipse.org/forums/index.php?t=thread&frm_id=271 or opening an issue at https://github.com/eclipse/smarthome/issues
