### ISSUE TITLE
MyOHClient: JSONObject["sitemap"] not a string 

### ISSUE THREAD

**Issue by robbyb67** [openhab/openhab1-addons#3772]
Since v1.8.0 I have a lot of lines like

ERROR o.o.i.m.internal.MyOHClient[:326]- JSONObject["sitemap"] not a string.

in openhab.log
The access via my.openhab.org works as expected so I assume this error is "cosmetically" but nevertheless annoying.
##

**Comment by kaikreuzer** [comment]
@belovictor Could you have a look?

**Comment by leiweke** [comment]
Same here with 1.8.1 .

my.openhab.org works fine

**Comment by spacemanspiff2007** [comment]
same here

**Comment by chrisknkc** [comment]
Same here.

**Comment by danielo515** [comment]
I am also getting a constant stream of this

**Comment by moskovskiy82** [comment]
Same issue
Openhab 1.8.1 running on ubuntu 14.04

**Comment by 9037568** [comment]
If someone could attach a debug log showing the problem, it might be helpful.

**Comment by ip-ua** [comment]
I have same issue -
I am using Openhab 1.8.3 and org.openhab.io.openhabcloud_1.9.0.201612192331.jar
openhab.log shows errors like this:
`[ERROR] [o.o.i.o.internal.CloudClient  ] - JSONObject["sitemap"] not a string.`
in openhab.log
Errors generated each time when I browsing to any subframe and returning back on the main page using Chrome or Firefox on PC. If I duing exactly same on my iPhone - no errors geterated.

**Comment by martenss** [comment]
Same issue here.
Running Openhab 2.0.0 on openhabian, browser is Firefox on PC.

openhabcloud.internal.CloudClient throws the "JSObject["sitemap"] not a string" error in openhab.log at every reload of a subframe with. I assume this is because the sitemap parameter then includes an '#' or '-', such as in https://myopenhab.org/classicui/app?sitemap=SitemapName#_0200.

At first load of https://myopenhab.org/classicui/app?sitemap=SitemapName there is no such error, but at re-load of this main page another error "Jetty request xxxxx failed: null" is thrown.

Openhabcloud is functional though, so indeed cosmetically.
