### ISSUE TITLE
Values returned from persistence are not exactly correct

### ISSUE THREAD

**Issue by DanielMalmgren** [openhab/openhab1-addons#5119]
I'm not 100% I'm reporting this at the correct place. The problem I'm seeing doesn't appear to be related to any specific persistence service but more to persistence in general.

I want to know per hour how much it has been raining, so I have these lines in an openhab rule:

        var Number valuenow = TellstickRainsensor_TotalRain.state
        var Number value1hago = TellstickRainsensor_TotalRain.historicState(now.minusHours(1)).state
        var Number lasthour = valuenow - value1hago

        logError("test", "Value one hour ago " + value1hago.toString)
        logError("test", "Value now " + valuenow.toString)
        logError("test", "Difference " + lasthour.toString)

Generally I expect "valuenow" and "value1hago" to be exactly the same if it hasn't been raining at all, which has often been the case lately, so the variable "lasthour" should generally be 0. Anyway, here are some examples of what I get in the log:

```
2017-02-18 20:00:00.034 [ERROR] [.eclipse.smarthome.model.script.test] - Value one hour ago 194.099999999999994315658113919198513031005859375
2017-02-18 20:00:00.042 [ERROR] [.eclipse.smarthome.model.script.test] - Value now 194.1
2017-02-18 20:00:00.048 [ERROR] [.eclipse.smarthome.model.script.test] - Difference 5.684341886080801486968994140625E-15

2017-02-27 08:00:00.309 [ERROR] [.eclipse.smarthome.model.script.test] - Value one hour ago 205.400000000000005684341886080801486968994140625
2017-02-27 08:00:00.313 [ERROR] [.eclipse.smarthome.model.script.test] - Value now 205.4
2017-02-27 08:00:00.317 [ERROR] [.eclipse.smarthome.model.script.test] - Difference -5.684341886080801486968994140625E-15
```

I've tried changing persistence. When the first example above was logged I used mysql persistence, now I'm on jdbc (still writing to mysql though). When I check directly in the mysql database the values are exactly correct (ie currently exactly 205.4).

As you can see there is not much difference, but it's enough to be wrong. 

I'm using openhab 2.0.0 and the persistence bindings I've used are 1.9.0 for both mysql and jdbc. OS is Debian 8.7 and mysql is 5.6.30 (on the same host).

**Comment by watou** [comment]
The behavior you note is implementation-specific and both MySQL and JDBC services pass historical DecimalType states through Java doubles, which cannot exactly represent most decimal numbers. The current state is an exact BigDecimal, so arithmetic leads to odd differences like you see.

Since double is used for performance, the simplest fix is to round the historic state to the precision you know the state should have into a new BigDecimal, or round the result of the arithmetic.

**Comment by DanielMalmgren** [comment]
So what you're saying is that this is by design and wont fix? From my point of view it's a little weird that you don't get out the same value that is put in, even though I can understand the reason. In my case I can round the result to one decimal and it will be right, but it feels more like a workaround than a solution.

**Comment by watou** [comment]
> So what you're saying is that this is by design and wont fix?

I doubt it's intentional, but possibly considered tolerable by the original persistence service authors, given the "natural" use of SQL DOUBLE type.  

In the case of the JDBC persistence service, you might be able to choose a different SQL data type as documented [here](http://docs.openhab.org/addons/persistence/jdbc/readme.html#configuration) by setting `sqltype.NUMBER` in your configuration.

> From my point of view it's a little weird that you don't get out the same value that is put in, even though I can understand the reason.

I also always thought it was weird to settle on an scheme for encoding floating point numbers that can't exactly represent the number, but it was chosen back in the era when alternatives were definitely too expensive.

> In my case I can round the result to one decimal and it will be right, but it feels more like a workaround than a solution.

Agreed, but the tradeoffs involved could consider that workaround to be better than the alternatives.

**Comment by DanielMalmgren** [comment]
Thanks a lot for the tip. Changed sqltype.NUMBER to DECIMAL(8,2), the numbers I get out are correct now.

Now I get two decimals for all items though, which is two decimals too much for for example my light sensor, which measures lux without decimals. Guess the optimal would be if this was configurable per item. But that's enough whining from me for now :-)

**Comment by watou** [comment]
Glad you found a workable configuration! :smile:
