### ISSUE TITLE
[twitter action] - sendDirectMessage fails

### ISSUE THREAD

**Issue by M1ch3L5** [openhab/openhab1-addons#5839]
Hello,

i want to use a rule to send a direct Message via twitter.

I have configured the twitter action as described in the tutorial. after that i am able to send tweets in my rule. As soon as i add/change to sendDirectMessage it fails. 

sendDirectMessage("@Name","Text")

I get the following Errormessage:
2019-03-22 11:43:00.607 [WARN ] [nhab.action.twitter.internal.Twitter] - Failed to send Tweet 'Text' because of :

If i go online ti the connected Twitteraccount, i can send directMessages to the User i want and everything is normal and ok.

I hope now to get some help.

Thanks.

**Comment by 9037568** [comment]
You should get a DEBUG log and then ask this question in the community forum.

**Comment by modestos** [comment]
Hi,

I have the exact same problem.
I enabled log level DEBUG for:
  org.openhab.action.twitter                         │ DEBUG

I get a similar message without any further info: 
2019-07-18 12:37:54.224 [WARN ] [nhab.action.twitter.internal.Twitter] - Failed to send Tweet 'TestMessage' because of : 

I get no other debug messages for the specific action even when turn on TRACE log level.
Any ideas?
