### ISSUE TITLE
Need basic guide! Or at least a sample config file and where to save it

### ISSUE THREAD

**Issue by leopheard** [openhab/openhab1-addons#5863]
Any basic help would be appreciated. I know the IP address of my DD-WRT, MAC, etc. but no idea how to set it up via this tutorial. Too many steps missed out.

**Comment by openhab-5iver** [comment]
Questions like this are best [asked in the forum](https://community.openhab.org/). Be sure to include more information than you did here in your issue (like which binding and OH version). If [the documentation](https://www.openhab.org/addons/bindings/network/#network-binding) is lacking in some way, mention what is missing in your post so that someone can include it, or click the link at the bottom of the page to make a contribution when you have things figured out.

**Comment by leopheard** [comment]
Thanks for the reply.

Basically, I've been trying to link the Smartthings to my openHAB running
on a RPI 3B+.

The section under usage:

"Configure the "MQTT Device" in the My Devices IDE
<https://graph.api.smartthings.com/device/list> with the IP Address, Port,
and MAC Address of the machine running the Docker container

There's more than one place to add the above details, and the guide doesn't
explain where to do it. Obviously under the android app under 'notify this
bridge' I can't select it, I'm assuming because the app can't communicate
with the openHAB IP.


Regards

Leo Edwards
