### ISSUE TITLE
item type request: push button (german: Taster)

### ISSUE THREAD

**Issue by Ma-580** [openhab/openhab1-addons#920]
Hi,

it would be nice to have push buttons (not toggle switches but switches sending an initial impulse only.)

e.g. for use with the WOL binding where a single impulse needs to be sent only / once only.
Using a toggle switch that changes its state does not make sense here.

further examples: media player control (Play, pause, ff, rev, rec)

**Comment by mknet** [comment]
Is it possible to set the mappings attribute also in the item definition directly? I'm asking since I want to add the Switch with a specific mapping to a group. If I do so, the mappings I set in the sitemap have no effect to the entry within the group and I get the default toggle button.

Many thanks

**Comment by watou** [comment]
> Is it possible to set the mappings attribute also in the item definition directly?

No, sorry!  Mappings have to be spelled out explicitly in the sitemap, so `Group item=...` will not suffice.

**Comment by mknet** [comment]
Sorry, I just removed my comment to this closed issue and created an new one:
https://github.com/openhab/openhab/issues/3876

Which approach is the right one, now? ;)
